### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by swithmn1** [Zolewit/TNN-matmul#2]
use caffe2onnx工具，出现TypeError: "int" object is not iterable，请问该怎么解决？

![image](https://user-images.githubusercontent.com/32815600/112992651-f0732080-919a-11eb-9f04-c89b278b1fbb.png)

**Comment by Zolewit** [comment]
你好，我没用过caffe2onnx
你可以用官方代码试试，如果不行，再在那边提issue。
https://github.com/Tencent/TNN
